spring.application.name=be
spring.datasource.url=jdbc:h2:file:./be/data/ecommerce
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Cố định username và password
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

logging.level.org.springframework.security=DEBUG
logging.level.com.example.be=DEBUG
logging.level.com.example.be.security=DEBUG


# --- Encoding ---
spring.http.encoding.enabled=true
spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8

# --- Đảm bảo servlet response UTF-8 ---
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
